CREATE TABLE IF NOT EXISTS ai_request_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '日志ID',
  user_id INT NOT NULL COMMENT '触发用户ID',
  username VARCHAR(100) COMMENT '触发用户名',
  trigger_type VARCHAR(50) NOT NULL COMMENT '触发类型：generation|generation_overview|generation_key_config|review|qa|agent|memory_refine|reflection',
  trigger_source VARCHAR(50) DEFAULT NULL COMMENT '触发来源标识：如agent_code、skill_name等',
  trigger_source_name VARCHAR(200) DEFAULT NULL COMMENT '触发来源显示名称',
  system_prompt MEDIUMTEXT COMMENT 'System提示词',
  user_prompt MEDIUMTEXT COMMENT 'User提示词',
  ai_response MEDIUMTEXT COMMENT 'AI输出结果',
  prompt_tokens INT DEFAULT 0 COMMENT '提示词Token数',
  completion_tokens INT DEFAULT 0 COMMENT '完成Token数',
  total_tokens INT DEFAULT 0 COMMENT '总Token数',
  model_name VARCHAR(100) COMMENT '使用的AI模型名称',
  status VARCHAR(20) NOT NULL DEFAULT 'success' COMMENT '状态：success|failed|timeout',
  error_message TEXT COMMENT '错误信息',
  execution_time_ms INT COMMENT '执行耗时（毫秒）',
  project_id INT DEFAULT NULL COMMENT '关联项目ID',
  library_id INT DEFAULT NULL COMMENT '关联用例库ID',
  module_id INT DEFAULT NULL COMMENT '关联模块ID',
  ip_address VARCHAR(50) COMMENT 'IP地址',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  
  INDEX idx_user_id (user_id),
  INDEX idx_trigger_type (trigger_type),
  INDEX idx_status (status),
  INDEX idx_created_at (created_at),
  INDEX idx_trigger_source (trigger_source),
  INDEX idx_composite_query (user_id, trigger_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI请求日志表-记录所有AI触发的Prompt和响应';
