CREATE TABLE IF NOT EXISTS ai_agent_tool_usage_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  username VARCHAR(100),
  item_type VARCHAR(20) NOT NULL COMMENT 'sub_agent | custom_tool',
  item_code VARCHAR(100) NOT NULL COMMENT 'agent_code 或 tool_name',
  item_name VARCHAR(200) COMMENT '显示名称',
  source VARCHAR(50) COMMENT '来源: review, qa, generation, test_run, agent_loop',
  execution_time_ms INT,
  prompt_tokens INT DEFAULT 0,
  completion_tokens INT DEFAULT 0,
  total_tokens INT DEFAULT 0,
  model_name VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'success',
  error_message TEXT,
  context_info JSON COMMENT '上下文信息如 libraryId, moduleId 等',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_item_type (item_type),
  INDEX idx_item_code (item_code),
  INDEX idx_user_id (user_id),
  INDEX idx_status (status),
  INDEX idx_created_at (created_at),
  INDEX idx_item_type_code (item_type, item_code),
  INDEX idx_source (source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
